### ISSUE TITLE
Deprecated selector in `json-colorer/styles/json-colorer.less`

### ISSUE THREAD

**Issue by michael-gracy** [akofman/json-colorer#1]
In `json-colorer/styles/json-colorer.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .source.json .meta.structure.dictionary.json` => `atom-text-editor.editor .syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary.syntax--json`

* `atom-text-editor::shadow .source.json .meta.structure.dictionary.json > .string.quoted.json` => `atom-text-editor.editor .syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary.syntax--json > .syntax--string.syntax--quoted.syntax--json`

* `atom-text-editor::shadow .source.json .meta.structure.dictionary.json > .value.json > .string.json` => `atom-text-editor.editor .syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary.syntax--json > .syntax--value.syntax--json > .syntax--string.syntax--json`

* `atom-text-editor::shadow .source.json .meta.structure.dictionary.json > .value.json > .array.json > .string.json` => `atom-text-editor.editor .syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary.syntax--json > .syntax--value.syntax--json > .syntax--array.syntax--json > .syntax--string.syntax--json`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by akofman** [comment]
Hello @michael-gracy,
Thanks for your issue, it should be ok now.
